services:
  db:
    image: postgres:15
    container_name: saferoom-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saferoom
      POSTGRES_DB: saferoom
  redis:
    image: redis:7
    container_name: saferoom-redis
    ports:
      - "6379:6379"